version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - ${POSTGRES_VOLUME}:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
    postgres:
