version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - ${POSTGRES_VOLUME}:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

volumes:
    postgres:
